version: '2'
services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - MYSQL_URL='root:root@tcp(172.17.0.2:3306)/contact?charset=utf8&parseTime=True'

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./data:/data/db
    environment:
      MYSQL_DATABASE: contact
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - "3306:3306"

  sidecar:
    build:
      context: ./envoy/.
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "8080:8080"
