version: '2'
services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - MYSQL_URL='root:root@tcp(172.17.0.2:3306)/contact?charset=utf8&parseTime=True'

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./data:/data/db
    environment:
      MYSQL_DATABASE: contact
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - "3306:3306"

  sidecar:
    build: envoyproxy/envoy-alpine:v1.7.0
    volumes:
      - ./front_envoy/envoy-config.yaml:/etc/envoy-config.yaml
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --v2-config-only -l info --service-cluster 'sidecar' --service-node 'sidecar' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"
    depends_on:
      - server
    ports:
      - "80:80"
      - "9901:9901"
