

apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: server
    tier: production
  sessionAffinity: None
type: LoadBalancer