---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sidecar
    envoy: "true"
  name: sidecar
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar
  template:
    metadata:
      labels:
        app: sidecar
        team: platform
        environment: production
        release: stable
        envoy: "true"
    spec:
      containers:
      - name: sidecar
        image: envoyproxy/envoy
        command: ["envoy"]
        args: ["-c", "/etc/envoy.yaml", "--service-cluster", "$(POD_NAME)"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: envoy-yaml
          mountPath: /etc/envoy.yaml
          subPath: envoy.yaml
      volumes:
      - name: envoy-yaml
        configMap:
          name: sidecar

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sidecar
  namespace: default
spec:
  selector:
    app: sidecar
  ports:
  - protocol: TCP
    port: 8001
    name: admin
  - protocol: TCP
    port: 80
    name: proxy